// <auto-generated />
using System;
using GoElectrify.DAL.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoElectrify.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031115037_AddColumnLastPingAtOfCharger")]
    partial class AddColumnLastPingAtOfCharger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoElectrify.BLL.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("ConnectorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("connector_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<int>("InitialSoc")
                        .HasColumnType("integer")
                        .HasColumnName("initial_soc");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_model_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ConnectorTypeId")
                        .HasDatabaseName("ix_bookings_connector_type_id");

                    b.HasIndex("VehicleModelId")
                        .HasDatabaseName("ix_bookings_vehicle_model_id");

                    b.HasIndex("StationId", "ScheduledStart")
                        .HasDatabaseName("ix_bookings_station_id_scheduled_start");

                    b.HasIndex("UserId", "ScheduledStart")
                        .HasDatabaseName("ix_bookings_user_id_scheduled_start");

                    b.ToTable("Bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Status_UPPER", "status = UPPER(status)");
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AblyChannel")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ably_channel");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("ConnectorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("connector_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DockSecretHash")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dock_secret_hash");

                    b.Property<string>("DockStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dock_status");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<DateTime?>("LastPingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ping_at");

                    b.Property<int>("PowerKw")
                        .HasColumnType("integer")
                        .HasColumnName("power_kw");

                    b.Property<decimal?>("PricePerKwh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_per_kwh");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_chargers");

                    b.HasIndex("ConnectorTypeId")
                        .HasDatabaseName("ix_chargers_connector_type_id");

                    b.HasIndex("LastPingAt")
                        .HasDatabaseName("ix_chargers_last_ping_at");

                    b.HasIndex("StationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_chargers_station_id_code");

                    b.ToTable("Chargers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Chargers_Status_UPPER", "status = UPPER(status)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 400,
                            Code = "FU-DC1",
                            ConnectorTypeId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 150,
                            PricePerKwh = 6500.0000m,
                            StationId = 300,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 401,
                            Code = "FU-AC1",
                            ConnectorTypeId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 22,
                            PricePerKwh = 4500.0000m,
                            StationId = 300,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 402,
                            Code = "FU-DC2",
                            ConnectorTypeId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 150,
                            PricePerKwh = 6500.0000m,
                            StationId = 300,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 403,
                            Code = "FU-DC3",
                            ConnectorTypeId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 150,
                            PricePerKwh = 6500.0000m,
                            StationId = 300,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 404,
                            Code = "FU-AC2",
                            ConnectorTypeId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 22,
                            PricePerKwh = 4500.0000m,
                            StationId = 300,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 410,
                            Code = "SC-DC1",
                            ConnectorTypeId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 200,
                            PricePerKwh = 6500.0000m,
                            StationId = 301,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 411,
                            Code = "SC-AC1",
                            ConnectorTypeId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 22,
                            PricePerKwh = 4500.0000m,
                            StationId = 301,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 420,
                            Code = "GP-DC1",
                            ConnectorTypeId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 120,
                            PricePerKwh = 6500.0000m,
                            StationId = 302,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 421,
                            Code = "GP-CHA1",
                            ConnectorTypeId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 50,
                            PricePerKwh = 6000.0000m,
                            StationId = 302,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 422,
                            Code = "GP-AC1",
                            ConnectorTypeId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DockStatus = "DISCONNECTED",
                            PowerKw = 22,
                            PricePerKwh = 4500.0000m,
                            StationId = 302,
                            Status = "ONLINE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ChargerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargerId")
                        .HasColumnType("integer")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Current")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("current");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<decimal?>("PowerKw")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("power_kw");

                    b.Property<DateTime>("SampleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sample_at");

                    b.Property<decimal?>("SessionEnergyKwh")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("session_energy_kwh");

                    b.Property<int?>("SocPercent")
                        .HasColumnType("integer")
                        .HasColumnName("soc_percent");

                    b.Property<string>("State")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Voltage")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("voltage");

                    b.HasKey("Id")
                        .HasName("pk_charger_logs");

                    b.HasIndex("ChargerId", "SampleAt")
                        .IsUnique()
                        .HasDatabaseName("ix_charger_logs_charger_id_sample_at");

                    b.ToTable("ChargerLogs", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ChargingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AblyChannel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ably_channel");

                    b.Property<decimal?>("AvgPowerKw")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("avg_power_kw");

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("ChargerId")
                        .HasColumnType("integer")
                        .HasColumnName("charger_id");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<decimal>("EnergyKwh")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("energy_kwh");

                    b.Property<int?>("FinalSoc")
                        .HasColumnType("integer")
                        .HasColumnName("final_soc");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("join_code");

                    b.Property<int?>("ParkingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("parking_minutes");

                    b.Property<int?>("SocEnd")
                        .HasColumnType("integer")
                        .HasColumnName("soc_end");

                    b.Property<int>("SocStart")
                        .HasColumnType("integer")
                        .HasColumnName("soc_start");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("RUNNING")
                        .HasColumnName("status");

                    b.Property<int?>("TargetSoc")
                        .HasColumnType("integer")
                        .HasColumnName("target_soc");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_charging_sessions");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_charging_sessions_booking_id");

                    b.HasIndex("ChargerId")
                        .IsUnique()
                        .HasDatabaseName("ux_charging_sessions_active_per_charger")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_charging_sessions_join_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_charging_sessions_status");

                    b.HasIndex("ChargerId", "StartedAt")
                        .HasDatabaseName("ix_charging_sessions_charger_id_started_at");

                    b.ToTable("ChargingSessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_charging_sessions_avg_power_non_negative", "avg_power_kw IS NULL OR avg_power_kw >= 0");

                            t.HasCheckConstraint("ck_charging_sessions_cost_non_negative", "cost IS NULL OR cost >= 0");

                            t.HasCheckConstraint("ck_charging_sessions_duration_non_negative", "duration_minutes >= 0");

                            t.HasCheckConstraint("ck_charging_sessions_energy_non_negative", "energy_kwh >= 0");

                            t.HasCheckConstraint("ck_charging_sessions_parking_non_negative", "parking_minutes IS NULL OR parking_minutes >= 0");

                            t.HasCheckConstraint("ck_charging_sessions_soc_range", "soc_start BETWEEN 0 AND 100 AND (soc_end IS NULL OR soc_end BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_charging_sessions_status_allowed", "status in ('PENDING','RUNNING','COMPLETED','ABORTED','TIMEOUT')");

                            t.HasCheckConstraint("ck_charging_sessions_status_upper", "status = UPPER(status)");

                            t.HasCheckConstraint("ck_charging_sessions_timespan", "ended_at IS NULL OR ended_at >= started_at");
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ConnectorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("MaxPowerKw")
                        .HasColumnType("integer")
                        .HasColumnName("max_power_kw");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_connector_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_connector_types_name");

                    b.ToTable("ConnectorTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DC fast (Combo 1)",
                            MaxPowerKw = 200,
                            Name = "CSS1",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DC fast (Combo 2)",
                            MaxPowerKw = 350,
                            Name = "CSS2",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAE J1772 (AC)",
                            MaxPowerKw = 7,
                            Name = "Type1-AC",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "IEC 62196-2 Type 2 (Mennekes)",
                            MaxPowerKw = 22,
                            Name = "Type2-AC",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DC fast (legacy/JDM)",
                            MaxPowerKw = 62,
                            Name = "CHAdeMO",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ExternalLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_logins_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_provider_user_id");

                    b.ToTable("ExternalLogins", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChargerId")
                        .HasColumnType("integer")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<int>("ReportedByStationStaffId")
                        .HasColumnType("integer")
                        .HasColumnName("reported_by_station_staff_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Response")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("response");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("ChargerId")
                        .HasDatabaseName("ix_incidents_charger_id");

                    b.HasIndex("ReportedByStationStaffId")
                        .HasDatabaseName("ix_incidents_reported_by_station_staff_id");

                    b.HasIndex("StationId", "Status")
                        .HasDatabaseName("ix_incidents_station_id_status");

                    b.ToTable("Incidents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Incidents_Status_UPPER", "status = UPPER(status)");
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_user_id_token_hash");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Driver",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Staff",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_stations_latitude_longitude");

                    b.HasIndex("Status", "Name")
                        .HasDatabaseName("ix_stations_status_name");

                    b.ToTable("Stations", null, t =>
                        {
                            t.HasCheckConstraint("ck_stations_status_values", "status IN ('ACTIVE','INACTIVE','MAINTENANCE')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 300,
                            Address = "7 Đ. D1, Long Thạnh Mỹ, Thủ Đức, Hồ Chí Minh 700000, Việt Nam",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nạp đầy năng lượng cho xe, sẵn sàng cho việc học! Trạm sạc xe điện hiện đại ngay trong khuôn viên Đại học FPT. Dành cho sinh viên, giảng viên và khách tham quan, giúp bạn sạc pin tiện lợi, an toàn trong giờ học và làm việc. Lựa chọn xanh cho một khuôn viên đại học thông minh.",
                            Latitude = 10.84167829167107m,
                            Longitude = 106.81083314772492m,
                            Name = "FPT University",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 301,
                            Address = "Số 1 Lưu Hữu Phước, Đông Hoà, Dĩ An, Hồ Chí Minh, Việt Nam",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Điểm sạc lý tưởng cho cộng đồng sinh viên năng động! Trạm sạc xe điện được đặt ngay tại Nhà Văn hóa Sinh viên TP.HCM. Bạn có thể an tâm sạc đầy pin trong khi tham gia các hoạt động, học nhóm hay uống cà phê. Nhanh chóng, an toàn và cực kỳ tiện lợi.",
                            Latitude = 10.876244851905408m,
                            Longitude = 106.80600195446553m,
                            Name = "Nhà Văn hóa Sinh viên TP.HCM",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 302,
                            Address = "TTTM Vincom Mega Mall Grand Park, 88 Phước Thiện, Long Bình, Thủ Đức, Hồ Chí Minh, Việt Nam",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mua sắm thả ga, không lo hết pin! Trạm sạc xe điện hiện đại nay đã có mặt tại Vincom Mega Mall Grand Park. Hãy sạc đầy pin cho xe trong lúc bạn và gia đình thỏa sức mua sắm, ăn uống và giải trí. Trải nghiệm tiện ích nhân đôi, cho chuyến đi thêm trọn vẹn.",
                            Latitude = 10.843429972631098m,
                            Longitude = 106.84260840302923m,
                            Name = "Vincom Mega Mall Grand Park",
                            Status = "ACTIVE",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.StationStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_station_staff");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_station_staff_station_id");

                    b.HasIndex("UserId", "StationId")
                        .IsUnique()
                        .HasDatabaseName("ix_station_staff_user_id_station_id");

                    b.ToTable("StationStaff", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("TotalKwh")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("total_kwh");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_name");

                    b.ToTable("Subscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            Name = "Go Spark – Basic",
                            Price = 360000m,
                            TotalKwh = 100m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            Name = "Go Pulse - Family",
                            Price = 690000m,
                            TotalKwh = 200m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            Name = "Go Drive – Pro",
                            Price = 3990000m,
                            TotalKwh = 1200m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            Name = "Go Flow – Flexible",
                            Price = 190000m,
                            TotalKwh = 50m,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_system_settings_key");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.TopupIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("OrderCode")
                        .HasMaxLength(128)
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("QrContent")
                        .HasColumnType("text")
                        .HasColumnName("qr_content");

                    b.Property<string>("RawWebhook")
                        .HasColumnType("text")
                        .HasColumnName("raw_webhook");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_topup_intents");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("ix_topup_intents_wallet_id_created_at");

                    b.ToTable("TopupIntents", null, t =>
                        {
                            t.HasCheckConstraint("CK_TopupIntents_Amount_NonNegative", "amount >= 0");

                            t.HasCheckConstraint("CK_TopupIntents_Status_UPPER", "status = UPPER(status)");
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("ChargingSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("charging_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("ChargingSessionId")
                        .HasDatabaseName("ix_transactions_charging_session_id");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("ix_transactions_wallet_id_created_at");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount_NonNegative", "amount >= 0");

                            t.HasCheckConstraint("CK_Transactions_Status_UPPER", "status = UPPER(status)");

                            t.HasCheckConstraint("CK_Transactions_Type_UPPER", "type = UPPER(type)");
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BatteryCapacityKwh")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("battery_capacity_kwh");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MaxPowerKw")
                        .HasColumnType("integer")
                        .HasColumnName("max_power_kw");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_models");

                    b.HasIndex("ModelName")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicle_models_model_name");

                    b.ToTable("VehicleModels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 200,
                            BatteryCapacityKwh = 42.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 60,
                            ModelName = "VinFast VF e34",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 201,
                            BatteryCapacityKwh = 19.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 32,
                            ModelName = "VinFast VF 3 Eco",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 202,
                            BatteryCapacityKwh = 22.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 37,
                            ModelName = "VinFast VF 3 Plus",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 203,
                            BatteryCapacityKwh = 37.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 100,
                            ModelName = "VinFast VF 5 Plus",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 204,
                            BatteryCapacityKwh = 59.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 150,
                            ModelName = "VinFast VF 6 Standard",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 205,
                            BatteryCapacityKwh = 59.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 160,
                            ModelName = "VinFast VF 6 Plus",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 206,
                            BatteryCapacityKwh = 75.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 180,
                            ModelName = "VinFast VF 7 Standard",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 207,
                            BatteryCapacityKwh = 75.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 200,
                            ModelName = "VinFast VF 7 Plus",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 208,
                            BatteryCapacityKwh = 87.7m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 150,
                            ModelName = "VinFast VF 8 Eco",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 209,
                            BatteryCapacityKwh = 92.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 170,
                            ModelName = "VinFast VF 8 Plus",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 210,
                            BatteryCapacityKwh = 92.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 200,
                            ModelName = "VinFast VF 9 Eco",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 211,
                            BatteryCapacityKwh = 123.0m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxPowerKw = 220,
                            ModelName = "VinFast VF 9 Plus",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.VehicleModelConnectorType", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_model_id");

                    b.Property<int>("ConnectorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("connector_type_id");

                    b.HasKey("VehicleModelId", "ConnectorTypeId")
                        .HasName("pk_vehicle_model_connector_types");

                    b.HasIndex("ConnectorTypeId")
                        .HasDatabaseName("ix_vehicle_model_connector_types_connector_type_id");

                    b.ToTable("VehicleModelConnectorTypes", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleModelId = 200,
                            ConnectorTypeId = 3
                        },
                        new
                        {
                            VehicleModelId = 200,
                            ConnectorTypeId = 1
                        },
                        new
                        {
                            VehicleModelId = 201,
                            ConnectorTypeId = 3
                        },
                        new
                        {
                            VehicleModelId = 201,
                            ConnectorTypeId = 1
                        },
                        new
                        {
                            VehicleModelId = 202,
                            ConnectorTypeId = 3
                        },
                        new
                        {
                            VehicleModelId = 202,
                            ConnectorTypeId = 1
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_user_id");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.WalletSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal>("RemainingKwh")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("remaining_kwh");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_subscriptions");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_wallet_subscriptions_subscription_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_wallet_subscriptions_wallet_id");

                    b.HasIndex("WalletId", "EndDate")
                        .HasDatabaseName("ix_wallet_subscriptions_wallet_id_end_date");

                    b.HasIndex("WalletId", "StartDate")
                        .HasDatabaseName("ix_wallet_subscriptions_wallet_id_start_date");

                    b.ToTable("WalletSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletSubscriptions_DateRange", "end_date >= start_date");

                            t.HasCheckConstraint("CK_WalletSubscriptions_RemainingKwh_NonNegative", "remaining_kwh >= 0");

                            t.HasCheckConstraint("CK_WalletSubscriptions_Status_UPPER", "status = UPPER(status)");
                        });
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Booking", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.ConnectorType", "ConnectorType")
                        .WithMany("Bookings")
                        .HasForeignKey("ConnectorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_connector_types_connector_type_id");

                    b.HasOne("GoElectrify.BLL.Entities.Station", "Station")
                        .WithMany("Bookings")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_stations_station_id");

                    b.HasOne("GoElectrify.BLL.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.HasOne("GoElectrify.BLL.Entities.VehicleModel", "VehicleModel")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_vehicle_models_vehicle_model_id");

                    b.Navigation("ConnectorType");

                    b.Navigation("Station");

                    b.Navigation("User");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Charger", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.ConnectorType", "ConnectorType")
                        .WithMany("Chargers")
                        .HasForeignKey("ConnectorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chargers_connector_types_connector_type_id");

                    b.HasOne("GoElectrify.BLL.Entities.Station", "Station")
                        .WithMany("Chargers")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chargers_stations_station_id");

                    b.Navigation("ConnectorType");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ChargerLog", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Charger", "Charger")
                        .WithMany("ChargerLogs")
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charger_logs_chargers_charger_id");

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ChargingSession", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Booking", "Booking")
                        .WithOne("ChargingSession")
                        .HasForeignKey("GoElectrify.BLL.Entities.ChargingSession", "BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_charging_sessions_bookings_booking_id");

                    b.HasOne("GoElectrify.BLL.Entities.Charger", "Charger")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charging_sessions_chargers_charger_id");

                    b.Navigation("Booking");

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ExternalLogin", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Incident", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Charger", "Charger")
                        .WithMany()
                        .HasForeignKey("ChargerId")
                        .HasConstraintName("fk_incidents_chargers_charger_id");

                    b.HasOne("GoElectrify.BLL.Entities.StationStaff", "ReportedBy")
                        .WithMany("IncidentsReported")
                        .HasForeignKey("ReportedByStationStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_station_staff_reported_by_station_staff_id");

                    b.HasOne("GoElectrify.BLL.Entities.Station", "Station")
                        .WithMany("Incidents")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_stations_station_id");

                    b.Navigation("Charger");

                    b.Navigation("ReportedBy");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.RefreshToken", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.StationStaff", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Station", "Station")
                        .WithMany("StationStaff")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_staff_stations_station_id");

                    b.HasOne("GoElectrify.BLL.Entities.User", "User")
                        .WithMany("StationStaff")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_station_staff_users_user_id");

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.TopupIntent", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Wallet", "Wallet")
                        .WithMany("TopupIntents")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topup_intents_wallets_wallet_id");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Transaction", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.ChargingSession", "ChargingSession")
                        .WithMany("Transactions")
                        .HasForeignKey("ChargingSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_charging_sessions_charging_session_id");

                    b.HasOne("GoElectrify.BLL.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_wallets_wallet_id");

                    b.Navigation("ChargingSession");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.User", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.VehicleModelConnectorType", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.ConnectorType", "ConnectorType")
                        .WithMany("VehicleModelConnectorTypes")
                        .HasForeignKey("ConnectorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_model_connector_types_connector_types_connector_type_id");

                    b.HasOne("GoElectrify.BLL.Entities.VehicleModel", "VehicleModel")
                        .WithMany("VehicleModelConnectorTypes")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_model_connector_types_vehicle_models_vehicle_model_id");

                    b.Navigation("ConnectorType");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Wallet", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("GoElectrify.BLL.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.WalletSubscription", b =>
                {
                    b.HasOne("GoElectrify.BLL.Entities.Subscription", "Subscription")
                        .WithMany("WalletSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_subscriptions_subscriptions_subscription_id");

                    b.HasOne("GoElectrify.BLL.Entities.Wallet", "Wallet")
                        .WithMany("WalletSubscriptions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_subscriptions_wallets_wallet_id");

                    b.Navigation("Subscription");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Booking", b =>
                {
                    b.Navigation("ChargingSession");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Charger", b =>
                {
                    b.Navigation("ChargerLogs");

                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ChargingSession", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.ConnectorType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Chargers");

                    b.Navigation("VehicleModelConnectorTypes");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Station", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Chargers");

                    b.Navigation("Incidents");

                    b.Navigation("StationStaff");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.StationStaff", b =>
                {
                    b.Navigation("IncidentsReported");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Subscription", b =>
                {
                    b.Navigation("WalletSubscriptions");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ExternalLogins");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StationStaff");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.VehicleModel", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("VehicleModelConnectorTypes");
                });

            modelBuilder.Entity("GoElectrify.BLL.Entities.Wallet", b =>
                {
                    b.Navigation("TopupIntents");

                    b.Navigation("Transactions");

                    b.Navigation("WalletSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
