# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    # Build the solution in Release so publish can use --no-build safely
    - name: Build (Release)
      run: dotnet build --no-restore -c Release

    - name: Test
      # Tests run against the already-built Release outputs
      run: dotnet test --no-build -c Release --verbosity normal

    - name: Publish API (create artifact)
      # Publish the API project (not the solution). Publishing a specific project allows using -o.
      run: dotnet publish ./GoElectrify.Api/GoElectrify.Api.csproj -c Release -o ./artifacts --no-build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-publish
        path: artifacts
        retention-days: 7
